### ISSUE TITLE
升了依赖没发新版本

### ISSUE THREAD

**Issue by alsotang** [JacksonTian/loader-connect#1]
https://github.com/JacksonTian/loader-connect/commit/7735fba015a64ac8ee920f953ab7f0ba8447f548

线上装的 less 还是依赖 graceful-fs@3.0.8

**Comment by JacksonTian** [comment]
没有break吧？

**Comment by alsotang** [comment]
graceful-fs 版本低的时候，npm i 有  warning

2016-05-05 16:34 GMT+08:00 Jackson Tian notifications@github.com:

**Comment by alsotang** [comment]
这算是弃坑了还是。。。？

**Comment by JacksonTian** [comment]
released.

**Comment by alsotang** [comment]
不得不吐槽啊，你 npm 升级了之后，github 没有  push 吧
